# Generated by Django 5.0.6 on 2024-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
