# Generated by Django 5.0.6 on 2024-07-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_user_cart_user_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_me',
            new_name='contact_no',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('cash on Delivery', 'cash on Delivery'), ('Khalti', 'Khalti')], max_length=200),
        ),
    ]
