# Generated by Django 5.0.6 on 2024-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash on Delivery', 'cash on Delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], max_length=200),
        ),
    ]
