# Generated by Django 5.0.6 on 2024-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash on Delivery', 'cash on Delivery'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti')], max_length=200),
        ),
    ]
